### ISSUE TITLE
go.mod specify tag but pulling failed

### ISSUE THREAD

**Issue by wei0313** [kubernetes/api#25]
Hi 

In my go.mod:
...
require (
github.com/golang/protobuf v1.3.1
**k8s.io/api kubernetes-1.13.5**
k8s.io/client-go v10.0.0
...}

However, when I build, I kept getting errors because it's pulling  "k8s.io/api/admissionregistration/v1alpha1 latest". I tried adding k8s.io/api/admissionregistration/v1alpha1 kubernetes-1.13.5, but it complained about no go.mod in api/addmissionregistration. Could you tell me how to solve this issue? Is my configuration done incorrectly? 

user@virt-8876$ go build test/client.go
go: finding k8s.io/api kubernetes-1.13.5
go: finding k8s.io/api/admissionregistration/v1alpha1 latest
go: finding k8s.io/api/admissionregistration latest
go: finding k8s.io/api latest
build command-line-arguments: cannot load k8s.io/api/admissionregistration/v1alpha1: cannot find module providing package k8s.io/api/admissionregistration/v1alpha1

**Comment by volker-raschek** [comment]
They are not adhering to the default go specifies when creating git tags. For this reason you can't add the right version to your go.mod.

> Modules must be semantically versioned according to semver, usually in the form v(major).(minor).(patch), such as v0.1.0, v1.2.3, or v1.5.0-rc.1. The leading v is required. If using Git, tag released commits with their versions. Public and private module repositories and proxies are becoming available (see FAQ below).
> Source: https://github.com/golang/go/wiki/Modules#modules 

Volker

**Comment by nikhita** [comment]
>  k8s.io/api kubernetes-1.13.5

@wei0313 go modules support only exists after >=`kubernetes-1.15.0`. You can only use Godeps or Glide with earlier versions.

Your current method should work with 1.15. You can find some more instructions here: https://github.com/kubernetes/client-go/blob/master/INSTALL.md.
